### ISSUE TITLE
Why the source is different from the submit on DebianArt?

### ISSUE THREAD

**Issue by syo093c** [julietteTaka/homeworld#1]
Excuse me. I love your work, and I want to use this wallpaper.
I found that this version is  **different from the submit on DebianArt**(url: https://wiki.debian.org/DebianArt/Themes/Homeworld).
Could you please upload all the versions with .svg format?
Thank a lot!

**Comment by syo093c** [comment]
Sorry, it's my fault. I use **ImageMagick** to convert .svg to .png with **'convert  homeworld_wallpaper_2560x1600.svg homeworld_wallpaper_2560x1600.png'**. And the picture looks different, but I don't know why. Here is the result that I convert from .svg.
![homeworld_wallpaper_2560x1600](https://user-images.githubusercontent.com/45763662/99414913-3fc65c00-2932-11eb-8b79-1739c9ca60f2.png)

**Comment by syo093c** [comment]
I finally use **Inkscape** , and get a correct result.

**Comment by julietteTaka** [comment]
Hi, Thank you for letting me know!
I don't know why the convert function do this to the image, but I'm glad Inkscape resolved it.
