### ISSUE TITLE
provide login/background-nologo.svg

### ISSUE THREAD

**Issue by sunweaver** [julietteTaka/homeworld#5]
@julietteTaka Hi. I am the upstream and Debian maintainer of one of Debian's login manager frontends called "arctica-greeter". I am currently getting my package ready for Homeworld theming.

The Arctica Greeters places the Debian Logo into the bottom left corner. In the past, I have done this manually. In the past (except from futurePrototype), login/background.svg did not have an image at all. In futurePrototype (buster theme), we had login/background.svg and login/background-nologo.svg.

Can you provide a login/background-nologo.svg for homeworld, as well? And make sure that it gets included into Debian's desktop-base artwork package? Thanks a lot.

**Comment by julietteTaka** [comment]
Hi @sunweaver ,

I'm on it!
Just to be sure, for the login and the background images, you need to have only background images, without the Debian logo and text ?

**Comment by sunweaver** [comment]
Hi Juliette,

> Hi @sunweaver ,
> 
> I'm on it!

Coolio!

> Just to be sure, for the login and the background images, you need to have only background images, without the Debian logo and text ?

I can't speak for all of Debian here, I only speak for the one LightDM Greeter Frontend called "Arctica Greeter" (looks like Ubuntu's Login Screen back in 2014, aka Unity Greeter). For Arctica Greeter, I need a background that does neither have logo nor text.

The greeter overlays a logo PNG (Debian logo + Debian 11 as text) in the bottom right corner. For this, I have already extracted the logo+text from one of your artwork drafts. (But maybe you'd like to revisit that). Again, this is only for one special application / Login Manager in Debian, not for the generic desktop-base package content.

light+love
Mike

**Comment by julietteTaka** [comment]
Hi @sunweaver 

Due to some issues on my side, I didn't had the time to provide your no-logo backgrounds in time for the freeze.
Do you wish that I update the repo as soon as I have them ? I still don't have all the resolutions of the background.

Sorry for the inconvenience.

**Comment by sunweaver** [comment]
Hi @julietteTaka,

it seems like someone from the Desktop Team already provided a background-nologo.svg [1] in the homeworld theme's folder in the desktop-base package.

Thus, closing this issue. Thanks!

Mike

[1] https://salsa.debian.org/debian-desktop-team/desktop-base/-/tree/master/homeworld-theme/login
