### ISSUE TITLE
"11" in blog/wiki banners depends on system font

### ISSUE THREAD

**Issue by astrosticks** [julietteTaka/homeworld#6]
The "11" text element in the blog/wiki banners requires Laudatio to be viewed correctly. Needs to be converted to paths like in the installer image.

What the wiki banner looks like in my browser:

![image](https://user-images.githubusercontent.com/32315760/129452111-c127d544-eec1-44a1-960a-576afdd21a5b.png)

**Comment by julietteTaka** [comment]
Thanks, I just add a new version of the file.
